### ISSUE TITLE
如何将tokens转化为特征图，然后进行可视化的呢？

### ISSUE THREAD

**Issue by 789as-syl** [erfect2020/TransformerPerceptualLoss#1]

**Comment by 789as-syl** [comment]
你好，这项工作给了我很大的启发，我想知道tokens是如何转化为特征图，然后进行可视化，这支持我后续的工作

**Comment by erfect2020** [comment]
感谢关注我们的工作。token 可视化的方式参考了论文[Deep ViT Features as Dense Visual Descriptors](https://github.com/ShirAmir/dino-vit-features)。

**Comment by 789as-syl** [comment]
> 感谢关注我们的工作。token 可视化的方式参考了论文[Deep ViT Features as Dense Visual Descriptors](https://github.com/ShirAmir/dino-vit-features)。

十分感谢您的回答，我刚刚去尝试了一下，我运行代码 将shape为[1,3,128,128]的图片输入，却得到shape为[1, 1, 3721, 384]的特征图，按道理应该是 128x128大小的特征，请问一下，是只需要按照以上代码运行即可，不需要进行任何调整嘛？

**Comment by erfect2020** [comment]
384是隐变量的维度。我们的论文中用的是ViT-B，其隐变量维度为768（对应tokenize为16*16*3）。
3721是token的个数。我们的论文训练使用256*256的patch，其tokenize的patch为16，共得到256个token。
