### ISSUE TITLE
About "pretrained_ckpt"

### ISSUE THREAD

**Issue by Redamancy0222** [erfect2020/TransformerPerceptualLoss#2]
Hello, can you publish the pretrained MAE model parameter files?Thanks

**Comment by erfect2020** [comment]
Well. The pretrained MAE is original from the [MAE repo](https://github.com/facebookresearch/mae). Just download the ViT-Base model.

**Comment by Redamancy0222** [comment]
Thanks your reply!!!

**Comment by erfect2020** [comment]
My pleasure. If this repo help you, please cite us.
