### ISSUE TITLE
Can u share the check point and opt file?

### ISSUE THREAD

**Issue by FallenLeaves-Creator** [erfect2020/TransformerPerceptualLoss#4]
Can u share the checkpoint and opt file?

**Comment by erfect2020** [comment]
Please refer to this [issue#2](https://github.com/erfect2020/TransformerPerceptualLoss/issues/2).

**Comment by erfect2020** [comment]
The image size depends on the pretrained checkpoint; the default is 224.

**Comment by FallenLeaves-Creator** [comment]
Thanks for your reply! It helps a lot!
